- raw: "dpkg-divert --divert /usr/bin/mandb.orig /usr/bin/mandb"

- name: "pimp/break man-db"
  copy:
    dest: "/usr/bin/mandb"
    content: "exit 0"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "installing prerequirements"
  apt:
    name:
      - "eatmydata"
      - "nfs-common"
      - "make"
      - "automake"
    state: "present"
    update_cache: true

